steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/currencycap-portal'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/currencycap-portal'
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'currencycap-portal'
      - '--image=gcr.io/$PROJECT_ID/currencycap-portal'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'

images:
  - 'gcr.io/$PROJECT_ID/currencycap-portal'

options:
  logging: CLOUD_LOGGING_ONLY