name: Run Python Script

# This workflow is triggered on cron schedule
# every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask requests

    - name: Run Flask app and get currencies
      run: |
        nohup flask run &  # Run Flask app in background
        sleep 5            # Wait for the server to start
        curl http://localhost:5000/get_currencies > currencies.json

    - name: Display the file content
      run: cat currencies.txt

    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: currencies
        path: currencies.txt
