name: Get Data

on:
  pull_request:
    branches:
      - master

jobs:
  update-currencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Update Currencies Data
        run: |
          python run.py > currencies_temp.json
          if jq -e . >/dev/null 2>&1 < currencies_temp.json; then
            mv currencies_temp.json currencies.json
          else
            echo "Invalid JSON. Keeping previous data."
            rm currencies_temp.json
          fi
          cat currencies.json

      - name: Update News Data
        run: |
          python news.py > news.json || { sleep 10 && python news.py > news.json; }
          cat news.json
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

      - name: Commit and Push Currency Data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add currencies.json
          git commit -m "Update currencies data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push News
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add news.json
          git commit -m "Update News data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}