name: Run Python Script

# every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Create virtual environment
      run: python3 -m venv .venv

    - name: Activate virtual environment and install dependencies
      run: |
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install Flask requests aiohttp

    - name: Run the app
      run: |
        source .venv/bin/activate
        nohup python run.py &
        sleep 10

    - name: Get currencies
      run: |
        curl http://localhost:5000/get_currencies > currencies.json

    - name: Display the file content
      run: cat currencies.json

    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: currencies
        path: currencies.json
