name: Get Data

on:
  schedule:
    - cron: '*/15 * * * *'

  workflow_dispatch:
    inputs:
      should-publish:
        type: boolean
        description: "Do you want to publish the data?"
        default: false

jobs:
  update-currencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Update Currencies & News Data
        if: ${{ github.event.inputs.should-publish == 'true' }}
        run: python run.py currencies > currencies.json && python run.py news > news.json
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

      - name: Commit and Push Currency Data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add currencies.json
          git commit -m "Update currencies data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push News
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add news.json
          git commit -m "Update News data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}