name: Get Data

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-currencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Export Currencies & News Data to JSON
        run: |
          python run.py > currencies.json || { sleep 10 && python run.py > currencies.json; }
          python news.py > news.json || { sleep 10 && python news.py > news.json; }
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add currencies.json
          git commit -m "Update currencies data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}