name: Update Currency Data

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'

  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data aggregator
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python run.py

      - name: Prepare API endpoints
        run: python prepare_api.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
          publish_branch: gh-pages
          force_orphan: true

      - name: Commit updated data to repository
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/
          git diff --staged --quiet || git commit -m "Update currency data [$(date '+%Y-%m-%d %H:%M:%S')]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
